// auto-generated by circomkit
pragma circom 2.2.3;

include "../show.circom";

component main {public[messageHash, predicateLen, predicateClaimRefs, predicateOps, predicateRhsIsRef, predicateRhsValues, tokenTypes, tokenValues, exprLen]} = Show(2, 2, 8, 64);
