// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'third_party/openac_mdoc_mobile_app.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1024229840;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mopro_flutter_bindings',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> openacMdocMobileAppBenchmarkResultsFormatSize({
    required BigInt bytes,
  });

  Future<String> openacMdocMobileAppGenerateSharedBlinds({
    required String documentsPath,
  });

  Future<String> openacMdocMobileAppGetCommWShared({
    required String documentsPath,
    required String circuitType,
  });

  Future<void> openacMdocMobileAppInitApp();

  Future<String> openacMdocMobileAppMoproHelloWorld();

  Future<ProofResult> openacMdocMobileAppProveMdoc({
    required String documentsPath,
  });

  Future<ProofResult> openacMdocMobileAppProveShow({
    required String documentsPath,
  });

  Future<ProofResult> openacMdocMobileAppReblindMdoc({
    required String documentsPath,
  });

  Future<ProofResult> openacMdocMobileAppReblindShow({
    required String documentsPath,
  });

  Future<BenchmarkResults> openacMdocMobileAppRunCompleteBenchmark({
    required String documentsPath,
  });

  Future<String> openacMdocMobileAppSetupMdocKeys({
    required String documentsPath,
  });

  Future<String> openacMdocMobileAppSetupShowKeys({
    required String documentsPath,
  });

  Future<bool> openacMdocMobileAppVerifyMdoc({required String documentsPath});

  Future<PresentationResult> openacMdocMobileAppVerifyPresentation({
    required String documentsPath,
  });

  Future<bool> openacMdocMobileAppVerifyShow({required String documentsPath});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ZkProofError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ZkProofError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ZkProofErrorPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> openacMdocMobileAppBenchmarkResultsFormatSize({
    required BigInt bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kOpenacMdocMobileAppBenchmarkResultsFormatSizeConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppBenchmarkResultsFormatSizeConstMeta =>
      const TaskConstMeta(
        debugName: "benchmark_results_format_size",
        argNames: ["bytes"],
      );

  @override
  Future<String> openacMdocMobileAppGenerateSharedBlinds({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMdocMobileAppGenerateSharedBlindsConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppGenerateSharedBlindsConstMeta =>
      const TaskConstMeta(
        debugName: "generate_shared_blinds",
        argNames: ["documentsPath"],
      );

  @override
  Future<String> openacMdocMobileAppGetCommWShared({
    required String documentsPath,
    required String circuitType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          sse_encode_String(circuitType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMdocMobileAppGetCommWSharedConstMeta,
        argValues: [documentsPath, circuitType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppGetCommWSharedConstMeta =>
      const TaskConstMeta(
        debugName: "get_comm_w_shared",
        argNames: ["documentsPath", "circuitType"],
      );

  @override
  Future<void> openacMdocMobileAppInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kOpenacMdocMobileAppInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> openacMdocMobileAppMoproHelloWorld() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kOpenacMdocMobileAppMoproHelloWorldConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppMoproHelloWorldConstMeta =>
      const TaskConstMeta(debugName: "mopro_hello_world", argNames: []);

  @override
  Future<ProofResult> openacMdocMobileAppProveMdoc({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_proof_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMdocMobileAppProveMdocConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppProveMdocConstMeta =>
      const TaskConstMeta(debugName: "prove_mdoc", argNames: ["documentsPath"]);

  @override
  Future<ProofResult> openacMdocMobileAppProveShow({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_proof_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMdocMobileAppProveShowConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppProveShowConstMeta =>
      const TaskConstMeta(debugName: "prove_show", argNames: ["documentsPath"]);

  @override
  Future<ProofResult> openacMdocMobileAppReblindMdoc({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_proof_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMdocMobileAppReblindMdocConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppReblindMdocConstMeta =>
      const TaskConstMeta(
        debugName: "reblind_mdoc",
        argNames: ["documentsPath"],
      );

  @override
  Future<ProofResult> openacMdocMobileAppReblindShow({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_proof_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMdocMobileAppReblindShowConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppReblindShowConstMeta =>
      const TaskConstMeta(
        debugName: "reblind_show",
        argNames: ["documentsPath"],
      );

  @override
  Future<BenchmarkResults> openacMdocMobileAppRunCompleteBenchmark({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_benchmark_results,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMdocMobileAppRunCompleteBenchmarkConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppRunCompleteBenchmarkConstMeta =>
      const TaskConstMeta(
        debugName: "run_complete_benchmark",
        argNames: ["documentsPath"],
      );

  @override
  Future<String> openacMdocMobileAppSetupMdocKeys({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMdocMobileAppSetupMdocKeysConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppSetupMdocKeysConstMeta =>
      const TaskConstMeta(
        debugName: "setup_mdoc_keys",
        argNames: ["documentsPath"],
      );

  @override
  Future<String> openacMdocMobileAppSetupShowKeys({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMdocMobileAppSetupShowKeysConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppSetupShowKeysConstMeta =>
      const TaskConstMeta(
        debugName: "setup_show_keys",
        argNames: ["documentsPath"],
      );

  @override
  Future<bool> openacMdocMobileAppVerifyMdoc({required String documentsPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMdocMobileAppVerifyMdocConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppVerifyMdocConstMeta =>
      const TaskConstMeta(
        debugName: "verify_mdoc",
        argNames: ["documentsPath"],
      );

  @override
  Future<PresentationResult> openacMdocMobileAppVerifyPresentation({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_presentation_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMdocMobileAppVerifyPresentationConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppVerifyPresentationConstMeta =>
      const TaskConstMeta(
        debugName: "verify_presentation",
        argNames: ["documentsPath"],
      );

  @override
  Future<bool> openacMdocMobileAppVerifyShow({required String documentsPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMdocMobileAppVerifyShowConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMdocMobileAppVerifyShowConstMeta =>
      const TaskConstMeta(
        debugName: "verify_show",
        argNames: ["documentsPath"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ZkProofError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ZkProofError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError;

  @protected
  ZkProofError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ZkProofErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ZkProofError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ZkProofErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BenchmarkResults dco_decode_benchmark_results(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 18)
      throw Exception('unexpected arr length: expect 18 but see ${arr.length}');
    return BenchmarkResults(
      mdocSetupMs: dco_decode_u_64(arr[0]),
      showSetupMs: dco_decode_u_64(arr[1]),
      generateBlindsMs: dco_decode_u_64(arr[2]),
      proveMdocMs: dco_decode_u_64(arr[3]),
      reblindMdocMs: dco_decode_u_64(arr[4]),
      proveShowMs: dco_decode_u_64(arr[5]),
      reblindShowMs: dco_decode_u_64(arr[6]),
      verifyMdocMs: dco_decode_u_64(arr[7]),
      verifyShowMs: dco_decode_u_64(arr[8]),
      mdocProvingKeyBytes: dco_decode_u_64(arr[9]),
      mdocVerifyingKeyBytes: dco_decode_u_64(arr[10]),
      showProvingKeyBytes: dco_decode_u_64(arr[11]),
      showVerifyingKeyBytes: dco_decode_u_64(arr[12]),
      mdocProofBytes: dco_decode_u_64(arr[13]),
      showProofBytes: dco_decode_u_64(arr[14]),
      mdocWitnessBytes: dco_decode_u_64(arr[15]),
      showWitnessBytes: dco_decode_u_64(arr[16]),
      agePredicateSatisfied: dco_decode_bool(arr[17]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  PresentationResult dco_decode_presentation_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PresentationResult(
      linked: dco_decode_bool(arr[0]),
      agePredicateSatisfied: dco_decode_bool(arr[1]),
      predicate: dco_decode_String(arr[2]),
    );
  }

  @protected
  ProofResult dco_decode_proof_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ProofResult(
      prepMs: dco_decode_u_64(arr[0]),
      proveMs: dco_decode_u_64(arr[1]),
      totalMs: dco_decode_u_64(arr[2]),
      proofSizeBytes: dco_decode_u_64(arr[3]),
      commWShared: dco_decode_String(arr[4]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  ZkProofError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ZkProofErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ZkProofError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ZkProofErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BenchmarkResults sse_decode_benchmark_results(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mdocSetupMs = sse_decode_u_64(deserializer);
    var var_showSetupMs = sse_decode_u_64(deserializer);
    var var_generateBlindsMs = sse_decode_u_64(deserializer);
    var var_proveMdocMs = sse_decode_u_64(deserializer);
    var var_reblindMdocMs = sse_decode_u_64(deserializer);
    var var_proveShowMs = sse_decode_u_64(deserializer);
    var var_reblindShowMs = sse_decode_u_64(deserializer);
    var var_verifyMdocMs = sse_decode_u_64(deserializer);
    var var_verifyShowMs = sse_decode_u_64(deserializer);
    var var_mdocProvingKeyBytes = sse_decode_u_64(deserializer);
    var var_mdocVerifyingKeyBytes = sse_decode_u_64(deserializer);
    var var_showProvingKeyBytes = sse_decode_u_64(deserializer);
    var var_showVerifyingKeyBytes = sse_decode_u_64(deserializer);
    var var_mdocProofBytes = sse_decode_u_64(deserializer);
    var var_showProofBytes = sse_decode_u_64(deserializer);
    var var_mdocWitnessBytes = sse_decode_u_64(deserializer);
    var var_showWitnessBytes = sse_decode_u_64(deserializer);
    var var_agePredicateSatisfied = sse_decode_bool(deserializer);
    return BenchmarkResults(
      mdocSetupMs: var_mdocSetupMs,
      showSetupMs: var_showSetupMs,
      generateBlindsMs: var_generateBlindsMs,
      proveMdocMs: var_proveMdocMs,
      reblindMdocMs: var_reblindMdocMs,
      proveShowMs: var_proveShowMs,
      reblindShowMs: var_reblindShowMs,
      verifyMdocMs: var_verifyMdocMs,
      verifyShowMs: var_verifyShowMs,
      mdocProvingKeyBytes: var_mdocProvingKeyBytes,
      mdocVerifyingKeyBytes: var_mdocVerifyingKeyBytes,
      showProvingKeyBytes: var_showProvingKeyBytes,
      showVerifyingKeyBytes: var_showVerifyingKeyBytes,
      mdocProofBytes: var_mdocProofBytes,
      showProofBytes: var_showProofBytes,
      mdocWitnessBytes: var_mdocWitnessBytes,
      showWitnessBytes: var_showWitnessBytes,
      agePredicateSatisfied: var_agePredicateSatisfied,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  PresentationResult sse_decode_presentation_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_linked = sse_decode_bool(deserializer);
    var var_agePredicateSatisfied = sse_decode_bool(deserializer);
    var var_predicate = sse_decode_String(deserializer);
    return PresentationResult(
      linked: var_linked,
      agePredicateSatisfied: var_agePredicateSatisfied,
      predicate: var_predicate,
    );
  }

  @protected
  ProofResult sse_decode_proof_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_prepMs = sse_decode_u_64(deserializer);
    var var_proveMs = sse_decode_u_64(deserializer);
    var var_totalMs = sse_decode_u_64(deserializer);
    var var_proofSizeBytes = sse_decode_u_64(deserializer);
    var var_commWShared = sse_decode_String(deserializer);
    return ProofResult(
      prepMs: var_prepMs,
      proveMs: var_proveMs,
      totalMs: var_totalMs,
      proofSizeBytes: var_proofSizeBytes,
      commWShared: var_commWShared,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    ZkProofError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ZkProofErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    ZkProofError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ZkProofErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_benchmark_results(
    BenchmarkResults self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.mdocSetupMs, serializer);
    sse_encode_u_64(self.showSetupMs, serializer);
    sse_encode_u_64(self.generateBlindsMs, serializer);
    sse_encode_u_64(self.proveMdocMs, serializer);
    sse_encode_u_64(self.reblindMdocMs, serializer);
    sse_encode_u_64(self.proveShowMs, serializer);
    sse_encode_u_64(self.reblindShowMs, serializer);
    sse_encode_u_64(self.verifyMdocMs, serializer);
    sse_encode_u_64(self.verifyShowMs, serializer);
    sse_encode_u_64(self.mdocProvingKeyBytes, serializer);
    sse_encode_u_64(self.mdocVerifyingKeyBytes, serializer);
    sse_encode_u_64(self.showProvingKeyBytes, serializer);
    sse_encode_u_64(self.showVerifyingKeyBytes, serializer);
    sse_encode_u_64(self.mdocProofBytes, serializer);
    sse_encode_u_64(self.showProofBytes, serializer);
    sse_encode_u_64(self.mdocWitnessBytes, serializer);
    sse_encode_u_64(self.showWitnessBytes, serializer);
    sse_encode_bool(self.agePredicateSatisfied, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_presentation_result(
    PresentationResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.linked, serializer);
    sse_encode_bool(self.agePredicateSatisfied, serializer);
    sse_encode_String(self.predicate, serializer);
  }

  @protected
  void sse_encode_proof_result(ProofResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.prepMs, serializer);
    sse_encode_u_64(self.proveMs, serializer);
    sse_encode_u_64(self.totalMs, serializer);
    sse_encode_u_64(self.proofSizeBytes, serializer);
    sse_encode_String(self.commWShared, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class ZkProofErrorImpl extends RustOpaque implements ZkProofError {
  // Not to be used by end users
  ZkProofErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ZkProofErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ZkProofError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ZkProofError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ZkProofErrorPtr,
  );
}
